# Generated by Django 2.2 on 2019-05-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190509_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='This book has no description!'),
        ),
    ]
